#!/usr/bin/env node
// Vendor the pi runtime that ships inside the Tau installer.
//
// Produces src-tauri/resources/pi-runtime/:
//   node/node.exe (Windows) | node/node (macOS/Linux)      — standalone Node runtime
//   node_modules/…/pi-coding-agent/dist/bundle/cli.js      — npm-installed pi
//   manifest.json                                          — version stamp
//
// tauri.conf.json maps that folder into the bundle as `pi-runtime/`, and the
// Rust probe chain (probe_vendored_dir) picks it up ahead of PATH lookups, so
// end users never need to install the pi CLI themselves.
//
// Usage:
//   node scripts/vendor-pi.mjs            # skip when the manifest already matches
//   node scripts/vendor-pi.mjs --force    # re-download / re-install
//   node scripts/vendor-pi.mjs --pi=0.85.1 --node=v22.23.2
//
// Note: run it through `node` (or `npm run vendor:pi -- --pi=…/--node=…`) —
// `npm run vendor:pi -- --force` does NOT work, npm swallows `--force` itself.
//
// The Node download matches the host platform: the win-x64 node.exe on
// Windows, the official <platform>-<arch> tarball elsewhere (extraction
// uses the system `tar`). Run from the repo root via `npm run vendor:pi`.

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
	copyFileSync,
	createWriteStream,
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { Readable } from "node:stream";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { pipeline } from "node:stream/promises";

const PI_VERSION_DEFAULT = "0.87.0";
// LTS, ≥20 required by pi. Floor is v22.15.0: zlib gained zstd support there
// (zlib.createZstdDecompress), and pi's HTTP client dies with an unhandled
// `TypeError: zlib.createZstdDecompress is not a function` as soon as any
// endpoint answers `Content-Encoding: zstd` — pi.dev's model catalog and
// version endpoints already do on the older runtime, which crash-loops the
// whole app on startup.
const NODE_VERSION_DEFAULT = "v22.23.2";

const args = process.argv.slice(2);
const force = args.includes("--force");
const opt = (name) => {
	const hit = args.find((a) => a.startsWith(`--${name}=`));
	return hit ? hit.split("=").slice(1).join("=") : undefined;
};
const PI_VERSION = opt("pi") ?? PI_VERSION_DEFAULT;
const NODE_VERSION = (opt("node") ?? NODE_VERSION_DEFAULT).replace(/^v?/i, "v");

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dest = resolve(root, "src-tauri", "resources", "pi-runtime");
const manifestPath = resolve(dest, "manifest.json");
const nodeExe = resolve(dest, "node", process.platform === "win32" ? "node.exe" : "node");
const cliJs = resolve(
	dest,
	"node_modules",
	"@earendil-works",
	"pi-coding-agent",
	"dist",
	"bundle",
	"cli.js",
);

const log = (...m) => console.log("[vendor-pi]", ...m);
const die = (m) => {
	console.error("[vendor-pi]", m);
	process.exit(1);
};

// A local package.json makes npm treat `dest` as the project root — without
// it, npm walks up to Tau's own package.json and installs into (and prunes!)
// the app's node_modules instead. The dependency MUST be declared here:
// `npm ci` validates the lockfile against package.json and installs nothing
// for a package.json without dependencies (a bare --package-lock-only
// install generates a lockfile that package.json never agrees to).
// Always rewritten so a version bump lands in the manifest too.
function ensureLocalPackageJson() {
	const pkgPath = resolve(dest, "package.json");
	writeFileSync(
		pkgPath,
		JSON.stringify(
			{
				name: "tau-pi-runtime",
				private: true,
				description: "Vendored pi runtime; generated by scripts/vendor-pi.mjs",
				dependencies: {
					"@earendil-works/pi-coding-agent": PI_VERSION,
				},
			},
			null,
			2,
		) + "\n",
	);
}

function manifestMatches() {
	if (!existsSync(manifestPath)) return false;
	try {
		const m = JSON.parse(readFileSync(manifestPath, "utf8"));
		return (
			m.pi === PI_VERSION && m.node === NODE_VERSION && existsSync(nodeExe) && existsSync(cliJs)
		);
	} catch {
		return false;
	}
}

/// Verify `filePath` against the official nodejs.org SHASUMS256.txt for this
/// release. This is the supply-chain anchor for the runtime we ship inside
/// the installer — without it, a compromised nodejs.org response (or CDN)
/// means arbitrary code execution on every user machine.
async function verifyShasums(filePath, artifactName) {
	const url = `https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt`;
	log(`verifying ${artifactName} against ${url}`);
	const res = await fetch(url, { redirect: "follow" });
	if (!res.ok) die(`SHASUMS256.txt download failed: HTTP ${res.status}`);
	const shasums = await res.text();
	const expected = shasums
		.split("\n")
		.map((l) => l.trim().split(/\s+/))
		.find((parts) => parts.length === 2 && parts[1] === artifactName)?.[0];
	if (!expected) die(`${artifactName} not listed in SHASUMS256.txt for ${NODE_VERSION}`);
	const actual = createHash("sha256").update(readFileSync(filePath)).digest("hex");
	if (actual !== expected) {
		die(
			`SHA256 MISMATCH for ${artifactName}: expected ${expected}, got ${actual} — refusing to vendor a tampered runtime`,
		);
	}
	log(`sha256 verified: ${actual.slice(0, 12)}…`);
}

async function downloadNode() {
	mkdirSync(dirname(nodeExe), { recursive: true });
	if (process.platform === "win32") {
		const url = `https://nodejs.org/dist/${NODE_VERSION}/win-x64/node.exe`;
		log(`downloading ${url}`);
		const res = await fetch(url, { redirect: "follow" });
		if (!res.ok) die(`node download failed: HTTP ${res.status} (${url})`);
		const out = createWriteStream(nodeExe);
		await pipeline(Readable.fromWeb(res.body), out);
		await verifyShasums(nodeExe, `win-x64/node.exe`);
	} else {
		const distName = `node-${NODE_VERSION}-${process.platform}-${process.arch}`;
		const url = `https://nodejs.org/dist/${NODE_VERSION}/${distName}.tar.gz`;
		log(`downloading ${url}`);
		const res = await fetch(url, { redirect: "follow" });
		if (!res.ok) die(`node download failed: HTTP ${res.status} (${url})`);
		const tmp = resolve(dest, ".node-download");
		rmSync(tmp, { recursive: true, force: true });
		mkdirSync(tmp, { recursive: true });
		const tarball = resolve(tmp, "node.tar.gz");
		await pipeline(Readable.fromWeb(res.body), createWriteStream(tarball));
		await verifyShasums(tarball, `${distName}.tar.gz`);
		const untar = spawnSync("tar", ["-xzf", tarball, "-C", tmp], { stdio: "inherit" });
		if (untar.status !== 0) die(`tar extraction failed (exit ${untar.status})`);
		renameSync(resolve(tmp, distName, "bin", "node"), nodeExe);
		chmodSync(nodeExe, 0o755);
		rmSync(tmp, { recursive: true, force: true });
	}
	const mb = (statSync(nodeExe).size / 1024 / 1024).toFixed(1);
	log(`${basename(nodeExe)} written (${mb} MB)`);
}

/// Guard the zstd floor at vendor time: pi's HTTP client calls
/// `zlib.createZstdDecompress()` whenever a response says
/// `Content-Encoding: zstd`, and on Node < v22.15.0 that throws an unhandled
/// `'error'` event that kills the process — crash-looping the app on startup.
function assertNodeHasZstd() {
	const probe = spawnSync(
		nodeExe,
		["-e", "process.stdout.write(typeof require('node:zlib').createZstdDecompress)"],
		{ encoding: "utf8" },
	);
	if (probe.status !== 0 || probe.stdout.trim() !== "function") {
		die(
			`${NODE_VERSION} has no zlib zstd support (needs >= v22.15.0) — pi would crash on zstd responses`,
		);
	}
	log(`node ${NODE_VERSION} supports zstd`);
}

// A committed lockfile pins the whole transitive dependency tree of the
// vendored pi package: without it, every build resolves fresh sub-dependency
// versions from the npm registry, so a hijacked upstream package ships inside
// the next installer. The file carries the pi version it was generated for;
// bumping PI_VERSION regenerates it (commit the result).
const lockfilePath = resolve(root, "scripts", "pi-runtime-lock.json");

function storedLockMatches() {
	if (!existsSync(lockfilePath)) return false;
	try {
		const lock = JSON.parse(readFileSync(lockfilePath, "utf8"));
		return (
			lock.packages?.["node_modules/@earendil-works/pi-coding-agent"]?.version === PI_VERSION
		);
	} catch {
		return false;
	}
}

function installPi() {
	log(`installing @earendil-works/pi-coding-agent@${PI_VERSION} into ${dest}`);
	mkdirSync(dest, { recursive: true });
	ensureLocalPackageJson();
	const npm = process.platform === "win32" ? "npm.cmd" : "npm";
	const baseArgs = ["--omit=dev", "--no-audit", "--no-fund", "--loglevel=error"];
	let res;
	if (storedLockMatches()) {
		// Pinned path: npm ci installs exactly the committed tree.
		log("using committed pi-runtime-lock.json (npm ci)");
		copyFileSync(lockfilePath, resolve(dest, "package-lock.json"));
		res = spawnSync(npm, ["ci", ...baseArgs], {
			cwd: dest,
			stdio: "inherit",
			shell: process.platform === "win32",
		});
	}
	if (!res || res.status !== 0) {
		if (res) log(`npm ci failed (exit ${res.status}) — falling back to npm install`);
		res = spawnSync(
			npm,
			["install", ...baseArgs, `@earendil-works/pi-coding-agent@${PI_VERSION}`],
			{ cwd: dest, stdio: "inherit", shell: process.platform === "win32" },
		);
		if (res.status !== 0) die(`npm install exited with ${res.status}`);
		// First install (or pi version bump): snapshot the resolved tree so the
		// next build is reproducible. Commit the updated lockfile.
		copyFileSync(resolve(dest, "package-lock.json"), lockfilePath);
		log(`wrote ${lockfilePath} — commit it to pin this dependency tree`);
	}
}

if (manifestMatches() && !force) {
	log(`already vendored (pi ${PI_VERSION}, node ${NODE_VERSION}) — nothing to do`);
	process.exit(0);
}

if (force) {
	rmSync(dest, { recursive: true, force: true });
	log("cleared previous runtime (--force)");
	mkdirSync(dest, { recursive: true });
}

await downloadNode();
assertNodeHasZstd();
installPi();

if (!existsSync(cliJs)) die(`pi entrypoint missing after install: ${cliJs}`);

writeFileSync(
	manifestPath,
	JSON.stringify(
		{ pi: PI_VERSION, node: NODE_VERSION, vendoredAt: new Date().toISOString() },
		null,
		2,
	) + "\n",
);
log(`done — pi ${PI_VERSION}, node ${NODE_VERSION} → ${dest}`);
