#!/usr/bin/env node
// Vendor the pi runtime that ships inside the Tau installer.
//
// Produces src-tauri/resources/pi-runtime/:
//   node/node.exe                                            — standalone Node runtime
//   node_modules/…/pi-coding-agent/dist/bundle/cli.js        — npm-installed pi
//   manifest.json                                            — version stamp
//
// tauri.conf.json maps that folder into the bundle as `pi-runtime/`, and the
// Rust probe chain (probe_vendored_dir) picks it up ahead of PATH lookups, so
// end users never need to install the pi CLI themselves.
//
// Usage:
//   node scripts/vendor-pi.mjs            # skip when the manifest already matches
//   node scripts/vendor-pi.mjs --force    # re-download / re-install
//   node scripts/vendor-pi.mjs --pi=0.85.1 --node=v22.14.0
//
// Windows-only by project convention (AGENTS.md): the Node download is the
// win-x64 build. Run from the repo root via `npm run vendor:pi`.

import { spawnSync } from "node:child_process";
import { createWriteStream, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { Readable } from "node:stream";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { pipeline } from "node:stream/promises";

const PI_VERSION_DEFAULT = "0.84.3";
const NODE_VERSION_DEFAULT = "v22.14.0"; // LTS, ≥20 required by pi

const args = process.argv.slice(2);
const force = args.includes("--force");
const opt = (name) => {
	const hit = args.find((a) => a.startsWith(`--${name}=`));
	return hit ? hit.split("=").slice(1).join("=") : undefined;
};
const PI_VERSION = opt("pi") ?? PI_VERSION_DEFAULT;
const NODE_VERSION = (opt("node") ?? NODE_VERSION_DEFAULT).replace(/^v?/i, "v");

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dest = resolve(root, "src-tauri", "resources", "pi-runtime");
const manifestPath = resolve(dest, "manifest.json");
const nodeExe = resolve(dest, "node", process.platform === "win32" ? "node.exe" : "node");
const cliJs = resolve(
	dest,
	"node_modules",
	"@earendil-works",
	"pi-coding-agent",
	"dist",
	"bundle",
	"cli.js",
);

const log = (...m) => console.log("[vendor-pi]", ...m);
const die = (m) => {
	console.error("[vendor-pi]", m);
	process.exit(1);
};

// A local package.json makes npm treat `dest` as the project root — without
// it, npm walks up to Tau's own package.json and installs into (and prunes!)
// the app's node_modules instead.
function ensureLocalPackageJson() {
	const pkgPath = resolve(dest, "package.json");
	if (!existsSync(pkgPath)) {
		writeFileSync(
			pkgPath,
			JSON.stringify(
				{ name: "tau-pi-runtime", private: true, description: "Vendored pi runtime; generated by scripts/vendor-pi.mjs" },
				null,
				2,
			) + "\n",
		);
	}
}

function manifestMatches() {
	if (!existsSync(manifestPath)) return false;
	try {
		const m = JSON.parse(readFileSync(manifestPath, "utf8"));
		return m.pi === PI_VERSION && m.node === NODE_VERSION && existsSync(nodeExe) && existsSync(cliJs);
	} catch {
		return false;
	}
}

async function downloadNode() {
	const url = `https://nodejs.org/dist/${NODE_VERSION}/win-x64/node.exe`;
	log(`downloading ${url}`);
	const res = await fetch(url, { redirect: "follow" });
	if (!res.ok) die(`node download failed: HTTP ${res.status} (${url})`);
	mkdirSync(dirname(nodeExe), { recursive: true });
	const out = createWriteStream(nodeExe);
	await pipeline(Readable.fromWeb(res.body), out);
	const mb = (statSync(nodeExe).size / 1024 / 1024).toFixed(1);
	log(`node.exe written (${mb} MB)`);
}

function installPi() {
	log(`npm install @earendil-works/pi-coding-agent@${PI_VERSION} into ${dest}`);
	mkdirSync(dest, { recursive: true });
	ensureLocalPackageJson();
	const npm = process.platform === "win32" ? "npm.cmd" : "npm";
	const res = spawnSync(
		npm,
		[
			"install",
			"--omit=dev",
			"--no-audit",
			"--no-fund",
			"--loglevel=error",
			`@earendil-works/pi-coding-agent@${PI_VERSION}`,
		],
		{ cwd: dest, stdio: "inherit", shell: process.platform === "win32" },
	);
	if (res.status !== 0) die(`npm install exited with ${res.status}`);
}

if (manifestMatches() && !force) {
	log(`already vendored (pi ${PI_VERSION}, node ${NODE_VERSION}) — nothing to do`);
	process.exit(0);
}

if (force) {
	rmSync(dest, { recursive: true, force: true });
	log("cleared previous runtime (--force)");
	mkdirSync(dest, { recursive: true });
}

await downloadNode();
installPi();

if (!existsSync(cliJs)) die(`pi entrypoint missing after install: ${cliJs}`);

writeFileSync(
	manifestPath,
	JSON.stringify(
		{ pi: PI_VERSION, node: NODE_VERSION, vendoredAt: new Date().toISOString() },
		null,
		2,
	) + "\n",
);
log(`done — pi ${PI_VERSION}, node ${NODE_VERSION} → ${dest}`);
